【FE課題】step3
NByamane/dept_design_fe_work01 pull request #3
Opened 2023-12-08 01:50 UTC by NByamane

**step3：step3：検索フォーム箇所を作成する。検索機能はまだ必要ありません。 - useRefを使って実装を行なってください。**
上記対応を行いました。

### 変更ファイル
- /booklog/src/App.css
- /booklog/src/App.tsx

### 関連issue
newbeescoltd/nb_study_react#12

2023-12-08 09:09 UTC, NBmaeda requested changes
Step3の作業ありがとうございます🎉
フォームの制御の要素も入ってきて、少し考えることが多くなってきたと思います。
コメントを使って自身の思考を言語化して整理するのは効果的で良いと思います👏

レビューの内容ですが、少しややこしいものも含まれています。
不明点等があればお気軽にご質問ください！💡

2023-12-08 09:09 UTC, NBmaeda commented on booklog/src/App.tsx
> +    const pushSearch = (event: React.FormEvent) => { //React.FormEventはformの発火イベントに関する型？らしい
ちゃんとイベントの型を調べられていて良いですね👏
`React.FormEvent`は[ジェネリクス](https://typescriptbook.jp/reference/generics)として`Element`の型も指定することができるので、それも指定してあげましょう。
イベントハンドラ用の定義の際に頻繁に使用するので、ここで記法に慣れておくと良いです。

2023-12-08 09:09 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const SearchComponent = () => {
コンポーネントを分割する場合は、別のファイルに切り分けた方が好ましいです。
別のファイルに切り分けることで「機能の分割」の他に「可読性の向上」も望めます。

2023-12-08 09:09 UTC, NBmaeda commented on booklog/src/App.tsx
> +          <input type="text" name='search-contents' id='search-contents' className='search-contents' placeholder='キーワードを入力して書籍を検索' ref={searchRef} value={searchValue} onChange={(e) => setSearchValue(
本行に関してのコメントですが、少し長くなるので複数の章に分けます。


## 1. イベントハンドラにアロー関数を渡す

イベントハンドラにアロー関数を渡すことに関しては少し注意が必要です。
[公式ドキュメント](https://legacy.reactjs.org/docs/faq-functions.html#arrow-function-in-render)にも書いてあるとおりパフォーマンスに影響が出る場合があります。

理由としては、コンポーネントの再レンダリングの際にアロー関数が再生成されることです。
アロー関数は無名関数であるため、厳密な関数の同一性が担保されなくなることも相まってパフォーマンスへの影響や思わぬ不具合が発生する場合があります。
これは以下のような方法で防ぐことができます。

- `function`キーワードを使って関数宣言を行ったものを、イベントハンドラに渡す。
- `useCallBack()`を使用して、再レンダリングの際の関数の再生成を防ぐ。→`useCallBack()`の[公式ドキュメント](https://ja.react.dev/reference/react/useCallback)

少々込み入った話になって理解し難いと思うので、Reactでは「レンダリング時に起きることを考慮できるか否かでパフォーマンスに差が生まれる」ということだけ頭の片隅にでも置いておくと、今後の学習の助けになると思います。
今回の件に関しては、改善策を次の章で述べます。

## 2. `SyntheticEvent`に関して

`SyntheticEvent`とは、「ブラウザのネイティブなイベントを、良い感じに調整してくれるラッパー」という感じで解釈して頂ければいいと思います。
例えば本行の処理を以下のような関数に切り出すとします。
```
function handleChange(e: React.ChangeEvent<HTMLInputElement>){
  setSearchValue(e.target.value)
}
```

上記の関数を`onChange={handleChange}`のような形で`input`要素に渡しても問題なく動作します。
これは、`SyntheticEvent`が自動的にイベントハンドラに渡されるためです。

このようにすれば引数を使用するためにアロー関数を使用する必要がなくなり、パフォーマンスへの影響も考えなくて良さそうです。
参考にしてみてください。

2023-12-08 09:09 UTC, NBmaeda commented on booklog/src/App.tsx
> +    const [searchValue, setSearchValue] = useState(''); //初期値は空で、ボタンを押した時にsetSearchValueを介して新しい値を設定
`setSearchValue()`を`input`要素の`onChange()`の際に毎回呼んでいますが、その影響で`input`要素に入力があるたびにApp全体の再レンダリングが行われており、パフォーマンス的にあまり好ましく無い状態です。
再レンダリングが行われる理由としては、`useState()`で定義しているstateが更新されるためです。

さて改善方法ですが、せっかく`searchRef`を使用しているのだからそれを利用できないかを考えてみても良いかもしれません。
つまり`value`の管理自体はReact側ではなく、`input`要素に委ねるという方向性です。これは「[非制御コンポーネント](https://ja.legacy.reactjs.org/docs/uncontrolled-components.html)」という考え方です。
対して`useState()`を使ってReact側で値を保持するコンポーネントを、「制御コンポーネント」と呼びます。
非制御コンポーネントであれば値の更新のたびに再レンダリングが行われないため、今回のユースケースであれば効果的だと思われます。
ふんわりとで良いので、「制御or非制御」といった指標があることをぜひ覚えておいて下さい。

また再レンダリングのタイミングは、[React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=ja)を使用することで確認ができます。
[こちらの記事](https://dev.classmethod.jp/articles/react-developer-tools/)に導入方法がまとめられているので、まだであければ参考にして導入して見てください。

2023-12-11 09:21 UTC, NByamane commented on booklog/src/App.tsx
> +          <input type="text" name='search-contents' id='search-contents' className='search-contents' placeholder='キーワードを入力して書籍を検索' ref={searchRef} value={searchValue} onChange={(e) => setSearchValue(
@NBmaeda 
useCallbackフックは、キャッシュに残して読み込みのたびに関数が再生成されるのを防ぐためのツール、という風に考えておいて大丈夫ですか…？🤔

「レンダリング時に起きることを考慮できるか否かでパフォーマンスに差が生まれる」メモメモ…_φ(･_･

2023-12-12 06:18 UTC, NBmaeda commented on booklog/src/App.tsx
> +          <input type="text" name='search-contents' id='search-contents' className='search-contents' placeholder='キーワードを入力して書籍を検索' ref={searchRef} value={searchValue} onChange={(e) => setSearchValue(
@NByamane 
> useCallbackフックは、キャッシュに残して読み込みのたびに関数が再生成されるのを防ぐためのツール
上記の認識で問題ないです！今回の課題では使う必要はないですが、頭に入れておいてください💡

2023-12-12 07:40 UTC, NBmaeda requested changes
修正対応ありがとうございます🎉
色々考えることが多くて大変かと思いますが、着実に良くなってきています！

完了まで後一歩というところですので、引続き確認・対応をお願いします🙏

2023-12-12 07:40 UTC, NBmaeda commented on booklog/src/Search.tsx
> +	const searchRef = useRef<HTMLInputElement>(null); //初期値としてnullを渡す。HTMLInputElementで参照する要素はinputだよ〜といってる。ジェネリクス型というらしい。。。
「ジェネリクス"型"」ではなく「ジェネリクス」という機能です。
関数の引数のように型を汎用的に扱うようにできる機能で、[こちら](https://typescriptbook.jp/reference/generics)のページに分かりやすくまとまっているのでぜひ参照してみてください。

2023-12-12 07:40 UTC, NBmaeda commented on booklog/src/Search.tsx
> +	}, [searchValue]);
変数`searchValue`で現在の検索キーワードの状態を管理し、`input`要素のchangeイベントの発生時に`handleChange()`関数でそれを書き換える処理ですね。
これでstateの書き換えによる不要な再レンダリングは行われなくなりました🎉いいですね👏

しかし逆に考えると、stateに応じてインターフェースの書き換えを実施しなくても良いのであれば、Reactで状態を管理しなくても問題ないとも言えます。
幸い`input`要素はそれ自身が状態を保持してくれるため、今回の仕様であれば状態管理はDOM(`input`要素)に任せることができます。

そのため変数`searchValue`と関数`handleChange()`を使用せず、関数`pushSearch()`では`searchRef.current.value`を利用する形にするとよりスッキリすると思います。

2023-12-12 07:40 UTC, NBmaeda commented on booklog/src/Search.tsx
> +	}, []);
`useCallback()`を使うのであれば、使用することによって逆にパフォーマンスが下がるケースに注意してください。
今回は今後のStepを鑑ると「使用する」で良いと思いますが、上記の処理だけであれば`useCallback()`を使用することによるパフォーマンスの向上はあまり見込めないと思います。

まずは設計も含めたそれ以外の処理の最適化を実施することを優先して、それでも改善できないパフォーマンスの問題があった場合は`useCallback()`等の使用を検討する、くらいで良いと思います。
少しややこしいhooksとはなるので、後回しで良いのでじっくり学習してみてください。

2023-12-13 08:20 UTC, NBmaeda approved these changes
全く問題ないと思います！対応ありがとうございます👏
Step3の完了、お疲れ様でした🎉

`useState()`や`useRef()`をはじめとした状態管理に関しては良く分からない部分も多いと思いますが、じっくり学びつつ適宜最適解を更新していく形で良いと思います。
他業務もある中大変かと思いますが、oneshiさんのペースで引き続き頑張っていきましょう💪

2023-12-13 08:27 UTC, merged