【FE課題】step4
NByamane/dept_design_fe_work01 pull request #4
Opened 2023-12-27 09:03 UTC by NByamane

**step4：step4：headerの読書時間タイマーを作成する。 - useEffectを使って実装を行なってください。**
上記対応を行いました。

### 変更ファイル
- /booklog/src/App.css
- /booklog/src/App.tsx
- /booklog/src/Timer.tsx

### 関連issue
newbeescoltd/nb_study_react#13

2023-12-28 10:30 UTC, NBmaeda requested changes
Step4の実装お疲れ様でした👏

useEffectは奥が深いので、 かなり頭を悩ませたのではないかと思います🤔
今回はコンポーネント全体がかなり複雑になってしまっていたので、もう少しシンプルに設計しなおせるようにFBを記載しました。

具体策はあまり書いていないので難しいかもしれませんが、大きい方針は記載したので悩んでみてください🙏
その上で不明点等があればいつでも聞いてください！
頑張っていきましょう💪

2023-12-28 10:30 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +			)}
ここの条件分岐がかなり冗長になってしまっているので、よりシンプルになるように工夫してみてください。
方針としては`p`要素は共通のものを使用し、テキストやCSSのためのクラスを変数に応じて分岐するように吸うと良いと思います。

2023-12-28 10:30 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +	const handleSelectChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
ボタン等のイベントハンドラに関数を登録する際は、[preventDefault](https://developer.mozilla.org/ja/docs/Web/API/Event/preventDefault)メソッドを使用した方が良いです💡

92行目でも「デフォルトのフォーム送信を抑制する」と書かれていますが、上記を行うことで本来のDOMの挙動を抑制することが できます。

2023-12-28 10:30 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +	const [selectedSeconds, setSelectedSeconds] = useState(5); // selectで選択した秒数を補完。初期値5
`time`と`selectedSeconds`は1つにまとめることができるように思います🤔
管理する状態が増えるほどコンポーネントの複雑さは増しますし、処理による負荷も大きくなります。
出来るだけ状態を少なくできるような設計を考えてみてください。

2023-12-28 10:30 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +	const [intervalId, setIntervalId] = useState<number | null>(null); //初期値nullで型はnumber or nullが入る
この変数は不要です💡
`IntervalID`はアプリケーションの状態ではないため、React側で管理する必要はないです。

useEffect内で変数`intervalId`を宣言すれば、コンポーネントが再レンダリングされた際も値が保持されます。
[こちらの記事](https://qiita.com/al_tarte/items/9f12f91afb74fe8ecb0e)が理解の助けになるかもしれませんので、余裕があれば一読してみてください。

2023-12-28 10:30 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +		let timeCount: number = 0; //timeCountは変更される変数なので、letを使用。初期値0。
この変数には、`setInterval()`の[戻り値](https://developer.mozilla.org/ja/docs/Web/API/setInterval#%E8%BF%94%E5%80%A4)が格納されるはずです。
そのためこの変数こそ、`intervalId`とした方が第三者からしてもわかりやすくなると思います💡

2023-12-28 10:30 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +		setTimerActive(true);
ここで変数`timerActive`が`true`になるため、それをトリガーに`useEffect()`内の処理が走ります。
しかし65行目で`setIntervalId(newIntervalId)`を行なっているため、`intervalId !== null`となり`useEffect()`内のinterval処理は行われません。

この`handleStartButton()`関数内の処理と、`useEffect()`内の処理とが競合しておりかなり複雑および冗長な設計になってしまっています。
`setInterval()`は`useEffect()`内で扱うものとして、もう一度設計をし直してみてください💡

2024-01-05 04:21 UTC, NByamane commented
@NBmaeda 
お疲れ様です！
レビューありがとうございました🙇‍♀️
脳みそ蕩けてます🫠🫠🫠
現状困っている部分があるので、一旦コミットさせていただきました🥲
質問させてください🙇‍♀️

11行目でselectを選択した際に発火するhandleSelectChangeの内容を記載しています。
timerActiveがfalseの時だけsetTimeを更新するようにこのような記述をしているのですが、現状の挙動が10秒, 15秒を選択した際、10秒切ったタイミング、15秒を切ったタイミングでselectで選択している部分が5秒, 10秒と更新されてしまいます😇

こちらを解消したいのですが、助言いただけないでしょうか😭
よろしくお願いいたします😞

2024-01-05 05:28 UTC, NBmaeda commented
> @NBmaeda お疲れ様です！ レビューありがとうございました🙇‍♀️ 脳みそ蕩けてます🫠🫠🫠 現状困っている部分があるので、一旦コミットさせていただきました🥲 質問させてください🙇‍♀️
> 
> 11行目でselectを選択した際に発火するhandleSelectChangeの内容を記載しています。 timerActiveがfalseの時だけsetTimeを更新するようにこのような記述をしているのですが、現状の挙動が10秒, 15秒を選択した際、10秒切ったタイミング、15秒を切ったタイミングでselectで選択している部分が5秒, 10秒と更新されてしまいます😇
> 
> こちらを解消したいのですが、助言いただけないでしょうか😭 よろしくお願いいたします😞

@NByamane 
select要素のvalue属性を確認すると`time`が指定されています。
`time`の値が「14,13,...」と変化するタイミングでコンポーネントの再レンダリングが走りselect要素も更新されるのですが、「5,10,15」以外の値に対応するoption要素が無いため、一番上のoption要素である「5秒」が表示されているだけだと思います💡

そもそもselect要素にはvalue属性は無いはずで、valueプロパティでは選択されているoption要素のvalueを取得できるようになっています。
ただReactの内部実装的な都合で、今回のような挙動になっているんじゃ無いかと予想しています🤔
value属性が使用できる要素一覧: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

そのため、select要素のvalue属性の指定から見直した方が良いかもしれません💡

2024-01-05 07:05 UTC, NByamane commented
@NBmaeda 
ありがとうございます🙇‍♀️
欲しい情報を取ってきたり付与したり考えて、余計な記述が多くなってますね、ごめんなさい😭
handleStartButton部分含め、このように修正してみましたがいかがでしょうか🙇‍♀️
getElementByIdなんて古の呪文を使ってますが…😇

>setInterval()はuseEffect()内で扱うものとして、もう一度設計をし直してみてください💡

この部分ですが、こういう意味合いであってますでしょうか？🤔

2024-01-05 07:58 UTC, NBmaeda reviewed
粘り強くご対応いただきありがとうございます🙏
直前のご質問に関して、修正いただいた内容を参照してご回答しています。

例によって直接的な解法を指摘するのは避けていますが、知りたければそれも含めて気軽にご質問してください💡

徐々にではありますが、着実に良くなってきています！
頭から火が出ているかもしれませんが...引き続き頑張っていきましょう💪🔥

2024-01-05 07:58 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +			const selectedOption = document.getElementById("reading-timer-select-box") as HTMLSelectElement;
> handleStartButton部分含め、このように修正してみましたがいかがでしょうか🙇‍♀️ getElementByIdなんて古の呪文を使ってますが…😇

ここの箇所ですが、`getElementById`はそもそも使用しない方が良いです🙅‍♂️
というのも、ReactはDOMの操作を独自の方法で最適化して行う為のライブラリです。
その中で例外的にDOMを直接JavaScriptで操作してしまうと、最適化できない箇所や思わぬバグ・不具合を生む可能性があります💡

ではReactでDOMを参照するにはどのようにすればいいでしょうか？
一つ前のStepで学んだことを思い出して、その内容が活用できないかを考えてみてください！
もし難しそうなら、[こちらの記事](https://ja.react.dev/reference/react/useRef)を参考にしてみてください。

2024-01-05 07:58 UTC, NBmaeda commented on booklog/src/Timer.tsx
>  	}, [timerActive, time]);
> > setInterval()はuseEffect()内で扱うものとして、もう一度設計をし直してみてください💡
> 
> この部分ですが、こういう意味合いであってますでしょうか？🤔

基本的にやっていることは合っていると思います👏
ただもう少し改善できる点はありそうです。

1. useEffect内のクリーンアップ関数を除くすべての処理は、`timerActive === true`の場合のみ作用します。
そのため、それ以外の場合は**早期return**をすることで無駄な処理やリソースの使用を防ぐことができます。

2. 1に伴って`intervalId`も改善することができます。
条件として`if (timerActive && time > 0)`としていますが、クリーンアップ関数で`intervalId`を利用する関係上`let`修飾子を使用していると思います。
1の処理を行った場合、条件は`time > 0`のみとなるため[三項演算子](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Conditional_operator)を使用することで`const`修飾子を使用できますし、宣言箇所を1行にまとめることができます。

`let`を使うと再代入できるメリットはありますが、特に複数人開発の場合は再代入できることが可読性の低下や思わぬ不具合につながったりすることがあります。
個人的には基本的に`const`を使用して、難しい場合は`let`を使うことを推奨しています。

2024-01-09 10:59 UTC, NByamane commented
@NBmaeda 
お疲れ様です！
レビューありがとうございます🙇‍♀️
再考してみましたので、ご確認の程よろしくお願いいたします🙏🙏🙏

2024-01-10 03:12 UTC, NBmaeda approved these changes
度重なる修正お疲れ様でした！
問題ないと思います、Step4完了です🎉
粘り強く対応してくれて大感謝です👏

1点ブラッシュアップできる点をコメントしましたので、確認してみてください。
引き続き頑張っていきましょう💪

2024-01-10 03:12 UTC, NBmaeda commented on booklog/src/Timer.tsx
> +		} else {
ここですが、if文の条件に合致する場合はreturnするため、その行以下の処理は実行されません。
ですのでelse句と`{}`を省略できます💡
また、以下のように書くこともできるので参考にしてみてください。

```
if (!timerActive) return;

// else節内の処理を書く。
```

2024-01-10 03:58 UTC, merged